# Generated by Django 3.0 on 2024-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traintype', models.CharField(choices=[('s', 'Select your Train Type'), ('Passenger', 'Passenger'), ('Vande_Bharat', 'Vande_Bharat')], default='s', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
