# Generated by Django 3.0 on 2024-03-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0002_auto_20240326_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='traindes',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='trainsrc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
