# Generated by Django 3.0 on 2024-04-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0003_auto_20240326_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='trainnum',
            field=models.IntegerField(blank=True, max_length=7, null=True),
        ),
    ]
