# Generated by Django 3.0 on 2024-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0005_auto_20240401_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='traindes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='trainnum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='trainsrc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
