# Generated by Django 3.0 on 2024-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0006_auto_20240401_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pno', models.CharField(blank=True, max_length=50, null=True)),
                ('noft', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
