# Generated by Django 3.0 on 2024-04-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0009_auto_20240407_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='arrtimedes',
        ),
        migrations.RemoveField(
            model_name='train',
            name='deptimesrc',
        ),
        migrations.AlterField(
            model_name='rform',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RRSApp.Train'),
        ),
    ]
