# Generated by Django 3.0 on 2024-04-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0014_auto_20240409_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='rform',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RRSApp.Train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='weekdays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
