# Generated by Django 3.2.5 on 2024-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0021_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfimg',
            field=models.ImageField(default='pfle.png', upload_to='Profiles/'),
        ),
    ]
