# Generated by Django 3.2.5 on 2024-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0022_user_pfimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='traintype',
            field=models.CharField(choices=[('s', 'Select your Train Type'), ('Passenger', 'Passenger'), ('Vande_Bharat', 'Vande_Bharat'), ('Express', 'Express'), ('Mail', 'Mail')], default='s', max_length=15),
        ),
    ]
