# Generated by Django 3.2.5 on 2024-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0023_alter_train_traintype'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='Title',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
